run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - revive
    - gosimple
    - ineffassign
    - typecheck
    - gosec
    - gocyclo
    - dupl
    - misspell
    - unparam
    - unconvert
    - goconst
    - goimports

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  exclude-use-default: false
